baseurl = ""
title = "Hi. I am Adrian"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/taghia.jpg"
  SEOTitle = "Adrian blogs"
  description = ""
  keyword = "Microservice, Data Science, Machine Learning"
  slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = "Sorry, the content you are looking for is not there anymore :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Data Scientist and passionate Climber"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/blog.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  #reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  #friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "adrian-garret-gabriel@web.de"
  linkedin       = "https://www.linkedin.com/in/adrian-gabriel-11636b100/"
  github         = "https://https://github.com/gabriead"
  xing          =  "https://www.xing.com/profile/Adrian_Gabriel4/cv"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  [[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "CLIMBING"
  href =  "/top/climbing/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
